landing/urls.py
from django.urls import path

from .views import vitalcen_landing_view, terms_view

app_name = 'landing'

urlpatterns = [
    path('', vitalcen_landing_view, name='home'),
    path('terms/', terms_view, name='terms')
]

vitalcen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing'))
]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render


def vitalcen_landing_view(request):
    context = {}
    return render(request, 'landing/vitalcen.html', context)


def terms_view(request):
    context = {'title': '| Terms'}
    return render(request, 'landing/terms.html', context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href='{% static "assets/ico/apple-touch-icon.png" %}'>
    <link rel="icon" type="image/png" sizes="32x32" href='{% static "assets/ico/favicon-32x32.png" %}'>
    <link rel="icon" type="image/png" sizes="16x16" href='{% static "assets/ico/favicon-16x16.png" %}'>
    <link rel="manifest" href='{% static "assets/ico/site.webmanifest" %}'>
    <link rel="mask-icon" href='{% static "assets/ico/safari-pinned-tab.svg" %}' color="#5bbad5">
    <link rel="shortcut icon" href='{% static "assets/ico/favicon.ico" %}'>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content='{% static "assets/ico/browserconfig.xml" %}'>
    <meta name="theme-color" content="#ffffff">

    {% block styles %}{% endblock %}

    <!-- Plugins CSS -->
    <link rel="stylesheet" href='{% static "assets/libs/flickity/dist/flickity.min.css" %}'>
    <link rel="stylesheet" href='{% static "assets/libs/flickity-fade/flickity-fade.css" %}'>
    <link rel="stylesheet" href='{% static "assets/libs/fullpage.js/dist/fullpage.min.css" %}'>
    <link rel="stylesheet" href='{% static "assets/libs/highlightjs/styles/codepen-embed.css" %}'>
    <link rel="stylesheet" href='{% static "assets/libs/@fortawesome/fontawesome-free/css/all.min.css" %}'>
    <link rel="stylesheet" href='{% static "assets/libs/incline-icons/style.min.css" %}'>

    <!-- Theme CSS -->
    <link rel="stylesheet" href='{% static "assets/css/theme.min.css" %}'>

    <title>{% block title %}Vitalcen{% endblock %}</title>
</head>
<body>
{% block content %}

{% endblock %}

<!-- JAVASCRIPT
    ================================================== -->
<!-- Global JS -->
<script src='{% static "assets/libs/jquery/dist/jquery.min.js" %}'></script>

<!-- Plugins JS -->
<script src='{% static "assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js" %}'></script>
<script src='{% static "assets/libs/flickity/dist/flickity.pkgd.min.js" %}'></script>
<script src='{% static "assets/libs/flickity-fade/flickity-fade.js" %}'></script>
<script src='{% static "assets/libs/jquery-parallax.js/parallax.min.js" %}'></script>
<script src='{% static "assets/libs/waypoints/lib/jquery.waypoints.min.js" %}'></script>
<script src='{% static "assets/libs/waypoints/lib/shortcuts/inview.min.js" %}'></script>
<script src='{% static "assets/libs/fullpage.js/vendors/scrolloverflow.min.js" %}'></script>
<script src='{% static "assets/libs/fullpage.js/dist/fullpage.min.js" %}'></script>
<script src='{% static "assets/libs/highlightjs/highlight.pack.min.js" %}'></script>

<!-- Theme JS -->
<script src={% static "assets/js/theme.min.js" %}></script>

{% block script %}{% endblock %}

</body>
</html>

templates/footer.html
<!-- FOOTER
================================================== -->
<section class="fp-section fp-auto-height">

    <footer class="section bg-dark">

    <!-- Triangles -->
    <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-left"></div>
    <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-right"></div>

    <!--Content -->
    <div class="container">
        <div class="row align-self-center">
            <div class="col-md">

                <!-- Links -->
                <ul class="list-unstyled list-inline text-md-right">
                    <li class="list-inline-item mr-2">
                        <a href="{% url 'landing:terms' %}" class="text-white">
                            Terminos y condiciones
                        </a>
                    </li>
                    <li class="list-inline-item mr-2">
                        <a href="{% url 'landing:terms' %}" class="text-white">
                            Privacidad
                        </a>
                    </li>
                </ul>

            </div>
        </div> <!-- / .row -->
        <div class="row align-items-center">
            <div class="col-md">

                <!-- Copyright -->
                <p class="text-white text-muted">
                    <small>
                        &copy; Copyright <span class="current-year"></span> AltimerX. Derechos reservados.
                    </small>
                </p>

            </div>
        </div> <!-- / .row -->
    </div> <!-- / .container -->

    </footer>
</section>

templates/navbar.html
{% load static %}

<!-- NAVBAR
================================================= -->
<nav class="navbar navbar-light">
    <div class="container">
        <!-- Brand -->
        <div>
            <img src="{% static 'assets/img/vitalcen/vitalcen_logo.png' %}" class="navbar-brand-img" alt="..." style="height: 80px">
        </div>
        <div class="ml-auto">
            {% if owner.whatsapp_link %}
                <!-- Social -->
                <a href="https://api.whatsapp.com/send?phone={{ owner.whatsapp_link }}" class="mr-4">
                    <i class="fab fa-whatsapp" style="color: green; font-size: 24px"></i>
                    <span class="d-none d-md-inline ml-2" style="color: green">
                    Whatsapp
                </span>
                </a>
            {% endif %}

            {% if owner.facebook_link %}
                <a href="https://www.facebook.com/{{ owner.facebook_link }}/" class="mr-4">
                    <i class="fab fa-facebook" style="color: dodgerblue; font-size: 24px"></i>
                    <span class="d-none d-md-inline ml-2" style="color: dodgerblue">
                    Facebook
                </span>
                </a>
            {% endif %}

            {% if owner.instagram_link %}
                <a href="https://www.instagram.com/{{ owner.instagram_link }}/" class="mr-4">
                    <i class="fab fa-instagram" style="color: mediumpurple; font-size: 24px"></i>
                    <span class="d-none d-md-inline ml-2" style="color: mediumpurple">
                    Instagram
                </span>
                </a>
            {% endif %}

            {% if owner.twitter_link %}
                <!-- Social -->
                <a href="https://www.twitter.com/={{ owner.twitter_link }}/" class="mr-4">
                    <i class="fab fa-twitter" style="color: lightblue; font-size: 24px"></i>
                    <span class="d-none d-md-inline ml-2" style="color: lightblue">
                    Twitter
                </span>
                </a>
            {% endif %}
        </div>
    </div> <!-- / .container -->
</nav>